version: '2'
services:
  api:
    build:
      context: ./nodeapp
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./nodeapp/src:/usr/src/nodeapp/src
      - /usr/src/nodeapp/node_modules
    ports:
      - "8080:8080"
      - "56745:56745"
    entrypoint: ["npm", "run", "develop"]
